spring;
config:
import:potional:file:.env[.properties]

cloud:
aws:
credentials:
access-key:${AWS_ACCESS_KEY_ID}
secret-kry:${AWS_SECRET_ACCESS_KEY}
region:
static:${AWS_REGION}
S3:
bucket: ${AWS_S3_BUCKET}