server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  datasource:
    url: jdbc:mariadb://localhost:6666/sonsing?userUnicode=true&characterEncoding=UTF-8
    username: sonsing_user
    password: sonsing_pw
    driver-class-name: org.mariadb.jdbc.Driver

app:
    cors:
        allowed-origins: "http://localhost:5173"

portone:
    api-key: ${0603811363534754}
    api-secret: ${wOeXgPOL7z1zlAqgArKHnCj5ZvtNllOaxec69CsPZndsTQKtIbkoLpdNerQOBjkpkQzuNCbvIPszl2Ea}
    webhook-secret:
